"""create maternal assessments table

Revision ID: 29a6a7aa073a
Revises: 73891c1eb60f
Create Date: 2026-09-22 13:08:19.110947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a6a7aa073a'
down_revision: Union[str, Sequence[str], None] = '73891c1eb60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maternal_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('systolicBP', sa.Integer(), nullable=False),
    sa.Column('diastolicBP', sa.Integer(), nullable=False),
    sa.Column('BS', sa.Float(), nullable=False),
    sa.Column('bodyTemp', sa.Float(), nullable=False),
    sa.Column('heartRate', sa.Integer(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('hb', sa.Float(), nullable=False),
    sa.Column('dietScore', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('calcium_mg', sa.Float(), nullable=False),
    sa.Column('iron_mg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maternal_assessments_id'), 'maternal_assessments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maternal_assessments_id'), table_name='maternal_assessments')
    op.drop_table('maternal_assessments')
    # ### end Alembic commands ###
