"""add assessment created timestamp

Revision ID: e2632f149724
Revises: d612e792ff2e
Create Date: 2026-09-22 19:29:18.139910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2632f149724'
down_revision: Union[str, Sequence[str], None] = 'd612e792ff2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'maternal_assessments',
    sa.Column(
        'created_at',
        sa.DateTime(),
        nullable=False,
        server_default=sa.text('CURRENT_TIMESTAMP')
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maternal_assessments', 'created_at')
    # ### end Alembic commands ###
